In [1]:
###################
#Lenovo L13       #
#python version3  #
#Mohamed Emam     #
#Protein filter   #
###################
#Import library
import pandas as pd
#Read the file
protein= pd.read_csv("/Users/mmansour/Desktop/raw_protein_data.csv")
#Add sum coloumn total
protein['Total'] = protein.sum(axis=1)

#Extract protein with zero value across the samples
remove_features = protein.loc[protein['Total'] == 0]
remove_features

,Unnamed: 0,1,2,3,4,6,8,9,11,13,...,36,38,39,40,43,44,45,46,48,Total
12,p13,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1618,p1620,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1685,p1687,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1703,p1705,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2223,p2225,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2682,p2685,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [2]:
#Filteration_of_removed_features_index
protein_features_index = remove_features.index
index_list = list(protein_features_index)
protein = protein.drop(protein.index[index_list])
protein= protein.iloc[0:, 0:(len(protein.columns)-1)]
#Export_csv
protein.to_csv("/Users/mmansour/Desktop/MS_filtered.csv", index=False)